# Autogenerated wrapper script for hpipm_jll for x86_64-w64-mingw32-march+avx512
export libhpipm

using blasfeo_jll
JLLWrappers.@generate_wrapper_header("hpipm")
JLLWrappers.@declare_library_product(libhpipm, "libhpipm.dll")
function __init__()
    JLLWrappers.@generate_init_header(blasfeo_jll)
    JLLWrappers.@init_library_product(
        libhpipm,
        "bin\\libhpipm.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
