# Autogenerated wrapper script for hpipm_jll for x86_64-linux-musl-march+avx
export libhpipm

using blasfeo_jll
JLLWrappers.@generate_wrapper_header("hpipm")
JLLWrappers.@declare_library_product(libhpipm, "libhpipm.so")
function __init__()
    JLLWrappers.@generate_init_header(blasfeo_jll)
    JLLWrappers.@init_library_product(
        libhpipm,
        "lib/libhpipm.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
